FROM node:10

COPY /frontend/minitwit/package*.json ./

RUN npm install

COPY /frontend/minitwit .

RUN npm run build

RUN rm -rf node_modules

RUN npm i -g serve

CMD (cd /build && serve --single -l 80)
