# This file is used by Travis-CI for the "test" phase to boot/run the containers for the "test" container
# This is NOT the file used on the server

version: '3.5'

networks:
  main:
    name: 'itu-minitwit-network'

services:

  db:
    image: onedevopsitu/db
    container_name: db
    networks:
      - main
    ports:
      - '27017:27017'

  backend:
    image: onedevopsitu/backend
    container_name: backend
    networks:
      - main
    depends_on:
      - db
    ports:
      - '3005:3005'
    environment:
      - DOCKER_NETWORK=enabled

  frontend:
    image: onedevopsitu/frontend
    container_name: frontend
    ports:
      - '3001:3001'

  prometheus:
    image: onedevopsitu/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - main

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    networks:
      - main
    ports:
      - 9100:9100
    restart: always


  grafana:
    image: onedevopsitu/grafana
    container_name: grafana
    ports:
      - "9111:3000"  
    networks:
      - main
    environment:
     - GF_SECURITY_ADMIN_USER=Helge&friends
     - GF_SECURITY_ADMIN_PASSWORD=uiUIui