version: '3.5'

services:

  db:
    image: onedevopsitu/db
    container_name: db
    ports:
      - '27017:27017'

  backend:
    image: onedevopsitu/backend # ${DOCKER_USERNAME}
    container_name: backend
    depends_on:
      - db
    ports:
      - '3005:3005'

  frontend:
    image: onedevopsitu/frontend
    container_name: frontend
    ports:
      - '3001:3001'
