FROM grafana/grafana:latest

COPY /monitoring/grafana/dashboards /var/lib/grafana/dashboards
COPY /monitoring/grafana/grafana.ini /etc/grafana/grafana.ini
COPY /monitoring/grafana/provisioning /etc/grafana/provisioning