FROM grafana/grafana:latest

COPY /mon-log/grafana/dashboards /var/lib/grafana/dashboards
COPY /mon-log/grafana/grafana.ini /etc/grafana/grafana.ini
COPY /mon-log/grafana/provisioning /etc/grafana/provisioning