{
 "title": "OneDevOpsV3",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "2XX's",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"2..\"}[$__range]))/sum(increase(http_request_duration_seconds_count[$__range]))*100"
    }
   ]
  },
  {
   "title": "3XX's",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"3..\"}[$__range]))/sum(increase(http_request_duration_seconds_count[$__range]))*100"
    }
   ]
  },
  {
   "title": "4XX's",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"4..\"}[$__range]))/sum(increase(http_request_duration_seconds_count[$__range]))*100"
    }
   ]
  },
  {
   "title": "5XX's",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"5..\"}[$__range]))/sum(increase(http_request_duration_seconds_count[$__range]))*100"
    }
   ]
  },
  {
   "title": "5XX's pr. path",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by (path)(http_request_duration_seconds_count{status_code=~\"5..\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "200's",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=\"200\"}[$__range]))/sum(increase(http_request_duration_seconds_count[$__range]))*100"
    }
   ]
  },
  {
   "title": "204's",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=\"204\"}[$__range]))/sum(increase(http_request_duration_seconds_count[$__range]))*100"
    }
   ]
  },
  {
   "title": "Avg. responsetime pr. path",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (path)(rate(http_request_duration_seconds_sum{path!~\"/swag.+\"}[5m]))/sum by (path)(rate(http_request_duration_seconds_count{path!~\"/swag.+\"}[5m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Avg. responsetime pr. status code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum by (status_code)(rate(http_request_duration_seconds_sum{path!~\"/swag.+\"}[1m]))/sum by (status_code)(rate(http_request_duration_seconds_count{path!~\"/swag.+\"}[1m]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Avg. Request Time (Path)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{path!~\"/swag.+\"}[5m])/rate(http_request_duration_seconds_count{path!~\"/swag.+\"}[5m])",
     "legendFormat": "{{path}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Request time (0.95Q)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{}[1m]))by (le))"
    }
   ]
  },
  {
   "title": "Request time (sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code)(rate(http_request_duration_seconds_sum[1m])/rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Request count (/sec.)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code)(rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code)(http_request_duration_seconds_count)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 37 },
   "targets": [
    {
     "expr": "mongodb_connections{state=\"current\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 37 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_instance_uptime_seconds{}"
    }
   ]
  },
  {
   "title": "Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_network_bytes_total{}[5m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "decmbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "mongodb_memory{type=~\"resident|virtual\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "System info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=~\"prometheus\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',job=~\"prometheus\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{job=~\"prometheus\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 53 },
   "targets": [
    {
     "expr": "avg(node_load5{}) /  count(count(node_cpu_seconds_total{}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 53 },
   "targets": [
    {
     "expr": "avg(node_load15) /  count(count(node_cpu_seconds_total{}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 53 },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{} * 100) / node_memory_MemTotal_bytes{})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 57 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 6, "w": 22, "x": 2, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user'}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait'}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle'}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "singlestat",
   "description": "Total RAM",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 63 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "node_memory_MemTotal_bytes{}" }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 22, "x": 2, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemTotal_bytes{}", "legendFormat": "RAM Total" },
    {
     "expr": "node_memory_MemTotal_bytes{} - node_memory_MemFree_bytes{} - (node_memory_Cached_bytes{} + node_memory_Buffers_bytes{})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{} + node_memory_Buffers_bytes{}",
     "legendFormat": "RAM Cache + Buffer"
    },
    { "expr": "node_memory_MemFree_bytes{}", "legendFormat": "RAM Free" },
    {
     "expr": "(node_memory_SwapTotal_bytes{} - node_memory_SwapFree_bytes{})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Filesystem space available",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs'}",
     "legendFormat": "{{mountpoint}} - Available"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs'} * 100) / node_filesystem_size_bytes{idevice!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "NginX", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Connections reading",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 80 },
   "targets": [
    { "expr": "nginx_connections_reading{}" }
   ]
  },
  {
   "title": "Connections writing",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 80 },
   "targets": [
    { "expr": "nginx_connections_writing{}" }
   ]
  },
  {
   "title": "Connections waiting",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 80 },
   "targets": [
    { "expr": "nginx_connections_waiting{}" }
   ]
  },
  {
   "title": "Accepted client connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "nginx_connections_accepted{job=\"nginx\"}"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 6, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginx_connections_active" }
   ]
  }
 ]
}