{
 "title": "OneDevOps",
 "time": { "from": "2020-03-12T05:37:02.007Z", "to": "2020-03-12T17:37:02.007Z" },
 "panels": [
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Get requests duration SUM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{method=\"GET\"}"
    }
   ]
  },
  {
   "title": "NginX",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Accepted client connections",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 1, "y": 1 },
     "targets": [
      { "expr": "nginx_connections_accepted" }
     ]
    },
    {
     "title": "Active connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 17, "x": 7, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "nginx_connections_active" }
     ]
    }
   ]
  }
 ]
}