{
 "title": "OneDevOpsV2",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "System info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=~\"prometheus\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',job=~\"prometheus\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{job=~\"prometheus\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "avg(node_load5{}) /  count(count(node_cpu_seconds_total{}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "avg(node_load15) /  count(count(node_cpu_seconds_total{}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{} * 100) / node_memory_MemTotal_bytes{})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total) by (cpu))"
    }
   ]
  },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "200's",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{status_code=\"200\"}"
    }
   ]
  },
  {
   "title": "204's",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{status_code=\"204\"}"
    }
   ]
  },
  {
   "title": "400's",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{status_code=\"400\"}"
    }
   ]
  },
  {
   "title": "500's",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{status_code=\"500\"}"
    }
   ]
  },
  {
   "title": "Request count (/sec.)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count[5m])",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Request time (sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m])",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Request time (sec.) (60 min.)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1h])) by (le))"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(http_request_duration_seconds_count)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  { "title": "NginX", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Connections reading",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 25 },
   "targets": [
    { "expr": "nginx_connections_reading{}" }
   ]
  },
  {
   "title": "Connections writing",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 25 },
   "targets": [
    { "expr": "nginx_connections_writing{}" }
   ]
  },
  {
   "title": "Connections waiting",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 25 },
   "targets": [
    { "expr": "nginx_connections_waiting{}" }
   ]
  },
  {
   "title": "Accepted client connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "nginx_connections_accepted{job=\"nginx\"}"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginx_connections_active" }
   ]
  }
 ]
}