{
 "title": "OneDevOpsV2",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"e1d0830b24b6:9100\",job=~\"prometheus\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"e1d0830b24b6:9100\",job=~\"prometheus\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"e1d0830b24b6:9100\",job=~\"prometheus\"}) by (cpu))"
    }
   ]
  },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "200's",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{status_code=\"200\"}"
    }
   ]
  },
  {
   "title": "204's",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{status_code=\"204\"}"
    }
   ]
  },
  {
   "title": "400's",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{status_code=\"400\"}"
    }
   ]
  },
  {
   "title": "404's",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{status_code=\"404\"}"
    }
   ]
  },
  {
   "title": "500's",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{status_code=\"500\"}"
    }
   ]
  },
  {
   "title": "Request count (/sec.) (last 5 min.)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count[5m])",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Request time (sec) (last 5 min.)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[5m])",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Request time (sec.) (60 min.)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1h])) by (le))"
    }
   ]
  },
  {
   "title": "Total requests (60 min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count[1h])",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "NginX",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Accepted client connections",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 1, "y": 1 },
     "targets": [
      { "expr": "nginx_connections_accepted" }
     ]
    },
    {
     "title": "Active connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 17, "x": 7, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "nginx_connections_active" }
     ]
    }
   ]
  }
 ]
}