version: '3.5'
networks:
  main:
    name: itu-minitwit-network
services:
  backend:
    image: onedevopsitu/backend # ${DOCKER_USERNAME}
    container_name: backend
    network_mode: host
    ports:
      - '3005:3005'
  frontend:
    image: onedevopsitu/frontend
    container_name: frontend
    networks:
      - main
    ports:
      - '3001:3001'