# This file is deployed to the server and used by Travis as the final step in "deploy" phase

version: '3.5'
networks:
  main:
    name: itu-minitwit-network
services:
  backend:
    image: onedevopsitu/backend # ${DOCKER_USERNAME}
    container_name: backend
    restart: always
    network_mode: host
    ports:
      - '3005:3005'
  frontend:
    image: onedevopsitu/frontend
    container_name: frontend
    restart: always
    networks:
      - main
    ports:
      - '3001:3001'

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - main

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    networks:
      - main
    ports:
      - 9100:9100
    restart: always


  grafana:
    image: onedevopsitu/grafana
    container_name: grafana
    ports:
      - "3000:3000"  
    networks:
      - main