version: '3.5'

networks:
  main:
    name: itu-minitwit-network

services:

  db:
    image: ${DOCKER_USERNAME}/db
    container_name: db
    networks:
      - main
    ports:
        - '27017:27017'

  backend:
    image: ${DOCKER_USERNAME}/backend
    container_name: backend
    networks:
      - main
    depends_on:
      - db
    ports:
      - '3005:3005'

  frontend:
    image: ${DOCKER_USERNAME}/frontend
    container_name: frontend
    networks:
      - main
    ports:
      - '3001:3001'
