version: '3.5'
networks:
  main:
    name: itu-minitwit-network
services:
  db:
    image: onedevopsitu/db
    container_name: db
    network_mode: host
    ports:
      - '27017:27017'
  backend:
    image: onedevopsitu/backend # ${DOCKER_USERNAME}
    container_name: backend
    network_mode: host
    ports:
      - '3005:3005'